[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3001

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
